export enum Constants {
    FETCH_COUNTRIES_REQUEST = "FETCH_COUNTRIES_REQUEST",
    FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS",
    FETCH_COUNTRIES_FAILURE = "FETCH_COUNTRIES_FAILURE",
    FILTER_COUNTRIES = "FILTER_COUNTRIES",
}
