export enum Constants {
  FETCH_COUNTRIES_REQUEST = "FETCH_COUNTRIES_REQUEST",
  FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS",
  FETCH_COUNTRIES_FAILURE = "FETCH_COUNTRIES_FAILURE",
  FILTER_COUNTRIES = "FILTER_COUNTRIES",
  ADD_FAVROITE_COUNTRIES = "ADD_FAVROITE_COUNTRIES",
  REMOVE_FAVORITE_COUNTRIES = "REMOVE_FAVORITE_COUNTRIES",
  SORT_COUNTRIES_NAME = "SORT_COUNTRIES_NAME",
  SORT_COUNTRIES_REGION = "SORT_COUNTRIES_REGION",
  SORT_COUNTRIES_POPULATION = "SORT_COUNTRIES_POPULATION",
  FETCH_COUNTRY_REQUEST = "FETCH_COUNTRY_REQUEST",
  FETCH_COUNTRY_SUCCESS = "FETCH_COUNTRY_SUCCESS",
  FETCH_COUNTRY_FAILURE = "FETCH_COUNTRY_FAILURE",
}
